### ISSUE TITLE
500 Error on monitor page

### ISSUE THREAD

**Issue by dwu-zingbox** [DeemOpen/zkui#11]
HTTP ERROR 500
Problem accessing /monitor. Reason:
    Server Error
Caused by:
java.lang.ArrayIndexOutOfBoundsException: 1
	at com.deem.zkui.controller.Monitor.doGet(Monitor.java:55)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:698)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1564)
	at com.deem.zkui.filter.AuthFilter.doFilter(AuthFilter.java:63)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1544)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:524)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:138)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:568)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1105)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:453)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1039)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:136)
	at org.eclipse.jetty.server.handler.HandlerList.handle(HandlerList.java:52)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:445)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:277)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:216)
	at org.eclipse.jetty.io.AbstractConnection$1.run(AbstractConnection.java:505)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:601)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:532)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dwu-zingbox** [comment]
Fresh install. First login as admin/manager

**Comment by dwu-zingbox** [comment]
Error message "NoNode for /appconfig/hosts" when accessing Hosts page.

Did I miss any configuration?

**Comment by arjunsurendra04** [comment]
/appconfig/hosts - You will need to create a node under /appconfig for "hosts"

You need this only if you plan to use it in the host -> property path format.
Which mean you have bunch of hosts 
host1.com points to /appconfig/path1
host2.com points to /appconfig/path2

**Comment by arjunsurendra04** [comment]
For the error on monitor page, looks like the zookeeper server in config file is not correct.Its not able to run stat on the zk server. Check it with

$ echo stat|nc -q 2 localhost 2181
Zookeeper version: 3.3.5-1301095, built on 03/15/2012 19:48 GMT
Clients:
 /127.0.0.1:62005[0](queued=0,recved=1,sent=0)

Latency min/avg/max: 0/0/0
Received: 4
Sent: 3
Outstanding: 0
Zxid: 0x4e5c
Mode: standalone
Node count: 20006
