### ISSUE TITLE
NoSuchMethodError org.slf4j.spi.LocationAwareLogger.log

### ISSUE THREAD

**Issue by mkjoerg** [DeemOpen/zkui#39]
I pulled the project and did a ```mvn clean install``` and then I wanted to start the container.
The code fails with following exception.

```sh
java -jar target/zkui-2.0-SNAPSHOT-jar-with-dependencies.jar
Exception in thread "main" java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;Ljava/lang/Throwable;)V
        at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:120)
        at com.googlecode.flyway.core.util.logging.apachecommons.ApacheCommonsLog.debug(ApacheCommonsLog.java:39)
        at com.googlecode.flyway.core.dbsupport.DbSupportFactory.createDbSupport(DbSupportFactory.java:59)
        at com.googlecode.flyway.core.Flyway.execute(Flyway.java:1177)
        at com.googlecode.flyway.core.Flyway.migrate(Flyway.java:819)
        at com.deem.zkui.dao.Dao.checkNCreate(Dao.java:56)
        at com.deem.zkui.Main.main(Main.java:61)
```

Have you encountered this error before?

**Comment by mkjoerg** [comment]
It seems, I just had an error with one change in the pom. Closing this.
