### ISSUE TITLE
Can not work in JDK1.8 environment, startup happen error : Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding.

### ISSUE THREAD

**Issue by tiandong19860806** [DeemOpen/zkui#81]
Hi ,
     When I run the zkui in JDK 1.8, the zkui happen error as below:

[root@CNT7XZKPD02 zkui-2.0]# java -jar ./zkui-2.0-SNAPSHOT-jar-with-dependencies.jar 
Exception in thread "main" java.lang.IllegalArgumentException: Malformed \uxxxx encoding.
        at java.util.Properties.loadConvert(Properties.java:574)
        at java.util.Properties.load0(Properties.java:391)
        at java.util.Properties.load(Properties.java:341)
        at com.deem.zkui.Main.main(Main.java:54)

Note:
1. OS system : CentOS 7.4 x64
2. JKD : java version "1.8.0_231"
3. ZooKeeper: 3.6.1

Picture as below:

1. zkui startup error
![image](https://user-images.githubusercontent.com/12596666/86113141-6c044c00-bafb-11ea-8c64-f58b19749ef6.png)

2. zkui config.cfg
![image](https://user-images.githubusercontent.com/12596666/86113204-8a6a4780-bafb-11ea-8447-6d350de4fdcc.png)

3. zkui build result success
![image](https://user-images.githubusercontent.com/12596666/86130039-286b0b80-bb16-11ea-80b5-6d142c64fcac.png)

**Comment by tiandong19860806** [comment]
Hi @gitorko 

     Maybe than class Main has a path issue , which is happen only in Linux and windows 10.
such as below,

1. fix before is Error
        File f = new File("config.cfg");
        if (f.exists()) {
            globalProps.load(new FileInputStream("config.cfg"));
        }

2. fix after is OK 
        String appConfPath = System.getenv("APP_CONF");
        if(appConfPath == null || appConfPath.length() == 0) {
        	System.out.println("env parameter APP_CONF isn't set, such as APP_CONF=/opt/zkui/zkui-2.0/ or actual path of zkui install");
        	return;
        }
        File f = new File(appConfPath + "config.cfg");
        if (f.exists()) {
            globalProps.load(new FileInputStream("config.cfg"));
        }


3. fix after is OK
![image](https://user-images.githubusercontent.com/12596666/86192711-c5f92600-bb7c-11ea-9144-9afe0f040da2.png)

**Comment by tiandong19860806** [comment]
note, a service to setting zkui

# 5. 设置开机自动启动，如下
cat > /etc/systemd/system/zkui.service <<EOF
[Unit]
Description=zkui-2.0 service
After=network.target
After=network-online.target
Wants=network-online.target

[Service]
User=zookeeper
Type=forking
TimeoutSec=0
Environment="ZKUI_HOME=/app/zkui/zkui-2.0/"
ExecStart=${JAVA_HOME}/bin/java -Xms128m -Xmx512m -XX:MaxMetaspaceSize=256m -jar /app/zkui/zkui-2.0/zkui-2.0-SNAPSHOT-jar-with-dependencies.jar
RestartSec=5
LimitNOFILE=1000000

[Install]
WantedBy=multi-user.target
EOF

![image](https://user-images.githubusercontent.com/12596666/86194508-373ad800-bb81-11ea-8e9c-df627a8e97fe.png)
